apiVersion: v1
kind: PersistentVolume
metadata:
  name: influx-data
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.volumeInfluxDataPath }}
status: {}
