apiVersion: 1

datasources:

  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    editable: true

  - name: InfluxDB
    type: influxdb
    access: proxy
    database: celery
    user: root
    url: http://influxdb:8086
    isDefault: true
    editable: true
    secureJsonData:
      password: root