# sources of the examples used
# https://github.com/bstiel/celery-docker
# https://github.com/vegasbrianc/prometheus


version: '3.4'

volumes:
  prometheus_data: {}
  influxdb_data: {}
  grafana_data: {}

services: 
  worker:
    build: .
    image: &img worker 
    command: [celery, worker, --app=worker.app]
    env_file:
      - praw_credentials.env
      - app_settings.env
    environment: &env      
      - CELERY_BROKER_URL=amqp://guest:guest@rabbitmq:5672 #protocol://rabbituser:password@rabbiturl
      - CELERY_RESULT_BACKEND=rpc
      - CELERY_WORKER_SEND_TASK_EVENTS=True
    depends_on:
      - rabbitmq
      - influxdb
    links:
      - influxdb
    volumes:
      - ./app:/app 
    restart: 'always'

  beat:
    build: .
    image: *img
    command: [celery, beat, --app=worker.app]
    env_file:
      - praw_credentials.env
      - app_settings.env
    environment: *env
    depends_on: 
      - rabbitmq
      - influxdb
    links:
      - influxdb
    volumes: 
      - ./app:/app
    restart: 'always'

  rabbitmq:
    image: rabbitmq:3.8
    environment: 
      - RABBITMQ_LOGS=./rabbit/rabbitlogs.conf
    restart: 'always'

  celery_exporter:
    image: ovalmoney/celery-exporter
    command: [--enable-events]
    environment:     
      - CELERY_EXPORTER_BROKER_URL=amqp://guest:guest@rabbitmq:5672
      - CELERY_EXPORTER_LISTEN_ADDRESS=0.0.0.0:8887
    ports:
      - "8887:8887"
    depends_on: 
      - rabbitmq
    restart: 'always'

  prometheus:
    image: prom/prometheus
    depends_on: 
      - celery_exporter
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      [
        --config.file=/etc/prometheus/prometheus.yaml,
        --log.level=warn,
        --storage.tsdb.path=/prometheus
      ]
    ports:
      - "9090:9090"
    links:
      - "celery_exporter"
      - "beat"
    restart: 'always'

  influxdb:
    image: influxdb:1.8.3
    environment: 
      - INFLUXDB_LOGGING_LEVEL=error
      - INFLUXDB_CONTINUOUS_QUERIES_LOG_ENABLED=false
      - INFLUXDB_DATA_QUERY_LOG_ENABLED=false
      - INFLUXDB_HTTP_LOG_ENABLED=false
    volumes:
      - influxdb_data:/var/lib/influxdb2
    ports:
      - "8086:8086"
    restart: 'always'

  grafana:
    image: grafana/grafana
    depends_on:
      - prometheus
      - influxdb
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/grafana.ini:/etc/grafana/grafana.ini
    environment: 
      - GF_LOG_LEVEL=error
    links:
      - prometheus
      - influxdb
    restart: always