apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f l5-tn19-kornelro/project/docker-compose.yaml
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: celery-exporter
  name: celery-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: celery-exporter
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f l5-tn19-kornelro/project/docker-compose.yaml
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: celery-exporter
    spec:
      containers:
        - args:
            - --enable-events
          env:
            - name: CELERY_EXPORTER_BROKER_URL
              value: amqp://guest:guest@rabbitmq:5672
            - name: CELERY_EXPORTER_LISTEN_ADDRESS
              value: 0.0.0.0:8887
          image: ovalmoney/celery-exporter
          name: celery-exporter
          ports:
            - containerPort: 8887
          resources: {}
      restartPolicy: Always
status: {}
