apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f l5-tn19-kornelro/project/docker-compose.yaml
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: influxdb
  name: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: influxdb
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f l5-tn19-kornelro/project/docker-compose.yaml
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: influxdb
    spec:
      containers:
        - env:
            - name: INFLUXDB_CONTINUOUS_QUERIES_LOG_ENABLED
              value: "false"
            - name: INFLUXDB_DATA_QUERY_LOG_ENABLED
              value: "false"
            - name: INFLUXDB_HTTP_LOG_ENABLED
              value: "false"
            - name: INFLUXDB_LOGGING_LEVEL
              value: error
          image: influxdb:1.8.3
          name: influxdb
          ports:
            - containerPort: 8086
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/influxdb2
              name: influxdb-data
      restartPolicy: Always
      volumes:
        - name: influxdb-data
          persistentVolumeClaim:
            claimName: influxdb-data
status: {}
