apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f l5-tn19-kornelro/project/docker-compose.yaml
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: redash-nginx
  name: redash-nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redash-nginx
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f l5-tn19-kornelro/project/docker-compose.yaml
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: redash-nginx
    spec:
      containers:
        - image: redash/nginx:latest
          name: redash-nginx
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
status: {}
