apiVersion: v1
data:
  POSTGRES_PASSWORD: "123"
  PYTHONUNBUFFERED: "0"
  REDASH_COOKIE_SECRET: "1212"
  REDASH_DATABASE_URL: postgresql://postgres:123@redash-postgres/postgres
  REDASH_LOG_LEVEL: ERROR
  REDASH_REDIS_URL: redis://redash-redis:6379/0
  REDASH_SECRET_KEY: "1212"
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: redash-adhoc-worker-redash-redash-env
  name: redash-redash-env
