apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f project-docker/docker-compose.yaml
    kompose.version: 1.22.0 (955b78124)
  creationTimestamp: null
  labels:
    io.kompose.service: flask-spark
  name: flask-spark
spec:
  replicas: {{ .Values.flaskSparkReplicaCount }}
  selector:
    matchLabels:
      io.kompose.service: flask-spark
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f project-docker/docker-compose.yaml
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.service: flask-spark
    spec:
      containers:
        - args:
            - spark-submit
            - app.py
          image: kornelro/lsdp6_spark
          name: flask-spark
          ports:
            - containerPort: 8080
          resources: {}
      restartPolicy: Always
status: {}
